build:
  tags:
    - kubernetes
  image: registry.gitlab.com/cscs-ci/stellar-group/hpx_docker/hpx-base
  script: 
    - cp -r $CI_PROJECT_DIR /code
    - |
      cmake /code \
            -B /build \
            -G "Ninja" \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_FLAGS="-O0 --coverage -fcolor-diagnostics" \
            -DCMAKE_EXE_LINKER_FLAGS="--coverage" \
            -DBUILD_TESTING=ON
    - cd /build && ninja
    - ctest
  after_script:
    - cd /build
    - grcov . -s /code -o $CI_PROJECT_DIR/coverage.json --llvm -t coveralls --service-name gitlab-ci --service-job-id $CI_JOB_ID --ignore-not-existing --prefix-dir /code --ignore "/*"
    - cat $CI_PROJECT_DIR/coverage.json | jq '.+ {"commit_sha": "$CI_COMMIT_SHA"}' | jq 'del(.service_number)' | jq 'del(.service_pull_request)' | jq '+ {"git": {"head": {"id": "$CI_COMMIT_SHA", "message": "$CI_COMMIT_MESSAGE"}}}' > $CI_PROJECT_DIR/coverage.json
    - curl --form "json_file=@$CI_PROJECT_DIR/coverage.json" --include https://coveralls.io/api/v1/jobs
  artifacts:
    when: always
    paths:
      - coverage.json
